import getpass
import colorama
from colorama import Fore
import discord
from discord.ext import commands
import os
import getpass
client = commands.Bot(command_prefix=commands.when_mentioned_or("$"))

os.system(f'cls & mode 85,20 & title PHAZIFY AUTOPRESSER')
user = input("Name: ")
print(f'''{Fore.BLUE}
 _    __   __    __   ______   ________  ______  ________  __      __ 
|       \ |  \  |  \ /      \ |        \|      \|        \|  \    /  |
| $$$$$$$\| $$  | $$|  $$$$$$\ \$$$$$$$$ \$$$$$$| $$$$$$$$ \$$\  /  $$
| $$__/ $$| $$__| $$| $$__| $$    /  $$   | $$  | $$__      \$$\/  $$ 
| $$    $$| $$    $$| $$    $$   /  $$    | $$  | $$  \      \$$  $$  
| $$$$$$$ | $$$$$$$$| $$$$$$$$  /  $$     | $$  | $$$$$       \$$$$   
| $$      | $$  | $$| $$  | $$ /  $$___  _| $$_ | $$          | $$    
| $$      | $$  | $$| $$  | $$|  $$    \|   $$ \| $$          | $$    
 \$$       \$$   \$$ \$$   \$$ \$$$$$$$$ \$$$$$$ \$$           \$$    
             ___________LOGGED IN AS: {user}___________                                             
                        PHAZIFY MADE THIS
                                                                                    
        ''' + Fore.GREEN)

token = input("Enter token: ")
sex = input("Keyword: ")
print("READY TO RAPE BLACKS")
###### CODEZZZZZ#######
@client.event
async def on_message(message):
    channel = message.channel
    print("BITCH GOT RAPED:",message.content)
    if message.content.endswith(sex):

     await message.channel.send('LOOLOOL SO THIS UNKNOWN NIGGA SPEAKING TO ME? https://cdn.discordapp.com/attachments/963221490034167912/963467038620254238/unknown.png')
     await message.channel.send('LMAAOOO OBEY YOUR ALMIGHTY FATHER START DIGGING YOUR GRAVE 💀💀💀')
     await message.channel.send('LOOL U AINT RDY FOR THIS REAL SHIT GO BACK TO PLAYING OSU')
     await message.channel.send('LMAAOOO I SLIPPED UR MOM THROAT OFF FAGGOT')
     await message.channel.send('LOOLOOOL I ROUGHLY HARDCORE FUCKED UR MOM')
     await message.channel.send('UR MOM PAINTED HER PUBES PINK U LGBTQ FUCK')
     await message.channel.send('LOOLOOOLLLL ? CHATMOVE WITH ME SON LOOOL')
     await message.channel.send('SON GOT GASSED IN THE GAS CHAMBER LOOL')
     await message.channel.send('UR MOMS A AMPUTEE JEWISH FUCK')
     await message.channel.send('I DID BRAWLHALLA COMBOS ON YOUR MOM LMAO')
     await message.channel.send('U FAT OBESE LOOKING ASS LOOL')
     await message.channel.send('CONTINUE PRODUCING CACAO IN NIGERIA AND CONTINUE PICKING UP COTTONS SON')
     await message.channel.send('UR BESTFRIEND IS A BARBIE DOLL 🤡🤡')
     await message.channel.send('I GOT MY OWN STATUE FAGGOT LMAAOOO U UNKNOWN FUCKER')
     await message.channel.send('DEFORMED SEA HORSE LOOKING ASS')
     await message.channel.send('YOU CANT COMPETE AGAINST A ABSOLUTE DEMON')
     await message.channel.send('WHY DID U THINK YOU COULD NOCLIP THROUGH A WALL IRL')
     await message.channel.send('SAY CHEESE 📸📸📸')
     await message.channel.send('UR MOM IS A SEX SLAVE')
     await message.channel.send('UR DAD IS A ASSASSIN MALESTRIPPER https://cdn.discordapp.com/attachments/963221490034167912/963474999761596476/6AC2B3B4-D129-4C10-AC20-CA7E57E8AF88.jpg')
     await message.channel.send('FOCUS GAYLORDIAN FAGGOT')
     await message.channel.send('FOCUS FUCKTARDED FAGGOT')
     await message.channel.send('U TIRED SON? GET A BLANKET PILLOW AND GO SLEEP')
     await message.channel.send('LOOLOOL 100 LIGHTYEARS REMAINING')
     await message.channel.send('RUN MY SHIT BACKWARDS SEED')
     await message.channel.send('YOUR MOMS A EBONY GIRL STFU PORNSTAR LOOKING ASS')
     await message.channel.send('UR MOM GOT A DISORDER CHARACTERIZED BY AN ABNORMALLY LOW BODY WEIGHT')
     await message.channel.send('LMAOOO U THINK YOU CAN OUTLAST ME??')
     await message.channel.send('YOURE ASS LMAOOO YOU CANT HANG WITH A DEMON')
     await message.channel.send('LOOOLOOLL UR GRANNY SEARCHING FOR ORGAMI DILDOS ON THE DARKWEB')
     await message.channel.send('UR AUNT IS A MILF GIRL')
     await message.channel.send('STUPID ASS UGLY ASS RAT LOOKING GOBLIN BUILD BITCH')
     await message.channel.send('U LOST A STARING CONTEST BATTLE TO YOURSELF IN THE MIRROR')
     await message.channel.send('U DOWNSYNDROME AUTISTIC DISABLED LOOKING ASS')
     await message.channel.send('YOU HAVE NO ASS YOURE A IRONING BOARD YOU STUPID BITCH')
     await message.channel.send('STFU U AFRO HAIR LOOKING ASS LMAO U BLACK 8 BALL LOOKING ASS')
     await message.channel.send('UR NIECE CHOCKED ON A HUGE MASSIVE 10 INCH COCK')
     await message.channel.send('UR MOM FINGERS HERSELF WITH A ELECTRIC VIBRATOR')
     await message.channel.send('STFU U BLACK NIGGER WITH THAT UGLY DOUBLE CHIN OF YOURS')
     await message.channel.send('UR AINT FELL OFF THE ROALERCOASTER AND HER FAT ASS STOMACH SAVED HER LIFE')
     await message.channel.send('UR MOM WAS JUMPING ROPE OVER HER OWN LEGS MY NIGGA U DUMB AS SHIT')
     await message.channel.send('UR BROTHER THOUGHT BEANS WOULD GIVE HIM SUPER SPEED DUMB ASS BOY')
     await message.channel.send('LOOOLOLOOL UR CURSE NUMBER IS 10 HOURS YOU CANT LAST')
     await message.channel.send('UR MOM WAS IN THE GALAXY AND GOT SUCKED UP BY A BLACK HOLE')
     await message.channel.send('JERK OFF ON A TRANNY THEN TALK BACK SON')
     await message.channel.send('CHEESESTICK LOOKING ASS LOOOLLOOL')
     await message.channel.send('I FUCKED UR MOM TILL SHE GOT PARALYSED')
     await message.channel.send('LOL UR ASS WAS LICKING THE HOSPITAL FLOOR AFTER YOU HEARD U GOT STAGE 4 OF CANCER')
     await message.channel.send('YOUR MOM FAINTED AFTER I UNCONSCIOUS SLAPPED HER WITH MY DICK')
     await message.channel.send('UR DAD NEEDS A HAIR TRANSPLANTATION https://cdn.discordapp.com/attachments/963221490034167912/963485098727059557/unknown.png')
     await message.channel.send('FOCUS MY GOON')
     await message.channel.send('WAKEY WAKEY FAGGOT')
     await message.channel.send('YOU WILL WAKE UP WITH A 10K ON YOUR NAME LOOLOOOLOLLOLLOOLOO')
     await message.channel.send('LITTLE MINION')
     await message.channel.send('LOOL SLEEP TIGHT FAGGOT https://tenor.com/view/packed-too-cool-for-school-ohma-phankiet12-gif-22568352')
     await message.channel.send('U IMMIGRANT FUCK GO SWIM BACK TO AFRICA')
     await message.channel.send('BUM ASS NIGGA LASTTTTT ???')
     await message.channel.send('MORON ASS NIGGA')
     await message.channel.send('FOCUS')
     await message.channel.send('FOCUS')
     await message.channel.send('FOCUS')
     await message.channel.send('FOCUS LOOL')
     await message.channel.send('MALNOURISHED FUCK')
     await message.channel.send('BEG ME TO SEND YOU A FOOD PACKET')
     await message.channel.send('LOOLOOL STFU UR MOMS ASS SMELLS LIKE SHRIMPS')
     await message.channel.send('SON U CANT OUTLAST ME LOOL')
     await message.channel.send('IMPOSSIBLE MISSION WINNING ME')
     await message.channel.send('IM UNDEFEATABLE FAGGOT')
     await message.channel.send('UNFOLDABLE')
     await message.channel.send('UNSTOPPABLE')
     await message.channel.send('LMAAOOO FUCKTARDED NIGLETS')
     await message.channel.send('GAYLORDIAN FAGGOT GO JERK UR BOYFRIENDS DICK OFF')
     await message.channel.send('I BACKFLIPPED YOUR MOM BACKWARDS')
     await message.channel.send('LOOLOOOL')
     await message.channel.send('U HAD A TRIO WITH SPONGEBOB PATRICK AND OCTO')
     await message.channel.send('EMIR HOEING UR SHIT')
     await message.channel.send('YOU CANT PRESSURE ME')
     await message.channel.send('HOP OFF THE CHAT AND HOP ON VC')
     await message.channel.send('UR BESTFRIEND IS A NICKELODEON CHARACTER')
     await message.channel.send('UR GONNA NEED YOGA TO CALM DOWN')
     await message.channel.send('UR STUCK WITH ME FOR A FEW MILLION LIGHTYEARS')
     await message.channel.send('RETARDED ASS NIGGA')
     await message.channel.send('TALIBAN RAILED UR MOM https://cdn.discordapp.com/attachments/963221490034167912/963529662653427752/unknown.png')
     await message.channel.send('STAY ON TRACK DONT GET OFF')
     await message.channel.send('DOGSHIT SHITTY PACKER')
     await message.channel.send('UR MOMS FIGHTING JINS SHES MENTALLY DISABLED')
     await message.channel.send('DIPSHIT ASS NIGGA ILL DIP YOU FAGGOT')
     await message.channel.send('ILL MAKE YOU EAT THE GROUND')
     await message.channel.send('YOURE GETTING SONNED BY UR FATHER')
     await message.channel.send('BEG YOUR FRIEND TO ACC HOP FOR YOU')
     await message.channel.send('YOUR PENETRATED MOTHER')
     await message.channel.send('LOOLO')
     await message.channel.send('OLOLOLO')
     await message.channel.send('LOLOLOL')
     await message.channel.send('LOLOL')
     await message.channel.send('OLOLOL')
     await message.channel.send('LOLOL')
     await message.channel.send('OLOL')
     await message.channel.send('OOLOL')
     await message.channel.send('LOLOL')
     await message.channel.send('YOUR BIRTH WAS A MISTAKE THE CONDOM BROKE')
     await message.channel.send('LOOLOOL ')
     await message.channel.send('I E FUCKED UR MOM SO ROUGHLY SHE GOT PREGNANT THROUGH BLUETOOTH CONNECTION')
     await message.channel.send('UR MOM GOT POISONED')
     await message.channel.send('UR MOMS A NAKED MOLE RAT https://cdn.discordapp.com/attachments/963221490034167912/963531294497714226/unknown.png')
     await message.channel.send('TRAGIC DEATH')
     await message.channel.send('NO ONE WILL VISIT YOUR GRAVEYARD LOOL')
     await message.channel.send('LOOOL BREAKDANCE ON ITS RAINING TACOS U WEIRD BUM')
     await message.channel.send('GO HOP ON ADOLF HITLERS DICK LOOLOOOLL')
     await message.channel.send('U CORNY FUCK')
     await message.channel.send('PUSSY ASS NIGGER')
     await message.channel.send('LOOLOOOL')
     await message.channel.send('LARRY THE LOBSTER SLIPPED OF YO DICK https://cdn.discordapp.com/attachments/963221490034167912/963532165965029396/unknown.png')
     await message.channel.send('🦀🦀🦀🦀🦀🦀🦀🦀🦀🦀🦀🦀🦀🦀🦀🦀🦀🦀🦀')
     await message.channel.send('LOOOLOOL UR MOM SQUIRTS A MIX OF CURRY KETCHUP MAYONAISE https://cdn.discordapp.com/attachments/963221490034167912/963532378255540225/unknown.png')
     await message.channel.send('LOOOLOOOOOLOLOLOLOLOLOLOL')
     await message.channel.send('SON IS SLEEP WALKING')
     await message.channel.send('WEAK ASS FOOTBALL NECROPHILIA')
     await message.channel.send('SON IS OVERWHELMED')
     await message.channel.send('UR MOMS BIG ASS FOREHEAD I RAN THE WHOLE PLAY OFFS ON IT + A TOUCH DOWN')
     await message.channel.send('U HIJACKED PIRATE BOATS U SOMALIAN FUCK')
     await message.channel.send('BIG CHUNGUS ASS LOOKING ASS')
     await message.channel.send('PEDU BUSTER LOOKING SHIT https://cdn.discordapp.com/attachments/963221490034167912/963534091381252157/unknown.png')
     await message.channel.send('PRAY THAT YOU WILL GET THROUGH THE NIGHT YOU FUCKING BAT')
     await message.channel.send('GORILLA LOOKING ASS BLACK ASS NIGGER BLACK THAN THE COLOUR BLACK')
     await message.channel.send('SPEAK TO ME WHEN YOU LOSE SOME SKIN TONE LOLLOOL 🤓🤓🤓🤓')
     await message.channel.send('LOLOLOOLOOL MY SON LOOL')
     await message.channel.send('WORSHIP ME ')
     await message.channel.send('OBEY ME')
     await message.channel.send('OR ELSE THE CONSEQUENCES WILL BE WORST')
     await message.channel.send('CHANGE UR MOMS MONTHLY NAPKIN')
     await message.channel.send('ROBLOX RO GANGSTER')
     await message.channel.send('UR MOMS THICK 10 MM BULLETPROOF ASS IS UNSTOPPABLE')
     await message.channel.send('KEEP RIDING ON THAT DICK YOU CANT BE SAVED')
     await message.channel.send('UR TRAPPED IN THE GC')
     await message.channel.send('DONT YAWN OR BLINK ')
     await message.channel.send('SHUT YOUR 2013 WINDOWS 7 I3 LOOKING ASS UP U FINNA PACK ON THAT POTATO PC?')
     await message.channel.send('U WEAK TWAT')
     await message.channel.send('GOBLIN BARBARIAN LOOKING SHIT')
     await message.channel.send('YOUR ANCESTORS GOT BOMBED BY THE SOVJET UNIE')
     await message.channel.send('UR ASS THOUGHT U WAS THE AVATAR TRYNA MASTER ALL THE 4 ELEMENTS https://cdn.discordapp.com/attachments/963221490034167912/963536933823320085/unknown.png')
     await message.channel.send('UR MOM ATE HIGHKICK IN THE ASS')
     await message.channel.send('RATIO L BOZO')
     await message.channel.send('UR MOMS A CHEAP PROSITUDE')
     await message.channel.send('LOOLOOL MONKEY ASS NIGGA ORANG OETANS LOOKING ASS')
     await message.channel.send('PHAZIFY IS UNSTOPPABLE')
     await message.channel.send('LL')
     await message.channel.send('OO')
     await message.channel.send('OOL')
     await message.channel.send('OOL')
     await message.channel.send('LLOO')
     await message.channel.send('LOL')
     await message.channel.send('OLOO')
     await message.channel.send('LOLO')
     await message.channel.send('LOLOL')
     await message.channel.send('OLOL')
     await message.channel.send('OOL')
     await message.channel.send('OOL')
     await message.channel.send('FOCUS')
     await message.channel.send('SEED')
     await message.channel.send('GOON FAGGOT')
     await message.channel.send('GHOST CHAT U AINT FAST ENOUGH U SPED')
     await message.channel.send('UR MOM GETTING RUSHED TO THE HOSPITAL ICU ILL SMACK THAT BITCH IN HER GRAVE')
     
     client.run(token, bot=False)
